spring:
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  groovy:
    template:
      cache: false
  datasource:
    url: jdbc:h2:file:~/dbatchDB
    username: sa
    password: abcd1234!
    driverclassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /db-console
  quartz:
    job-store-type: jdbc
    auto-startup: true
    jdbc:
      comment-prefix: QRTZ_
  devtools:
    livereload:
      enabled: true